#!/bin/sh

mkdir -p /proc /sys /dev/pts /tmp
ln -s /proc/mounts /etc/mtab

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts

mknod /dev/null c 1 3
mknod /dev/tty c 5 0

sleep 10

mdev -s

echo
udhcpc -i eth0 -s /etc/udhcpc.script -f -q

hole

mkdir /sobun

exec setsid cttyhack sh

